### ISSUE TITLE
Possibility to use custom datasets

### ISSUE THREAD

**Issue by lauritowal** [bigscience-workshop/promptsource#842]
Hi - I have a custom dataset (e.g. https://huggingface.co/datasets/lauritowal/redefine-math) and would like to create prompts for it by using PromptSource:

```
-Download the repo
-Navigate to the root directory of the repo
-Run pip install -e . to install the promptsource module
```

It seems there is no option for loading a custom dataset into the tool via the Web-GUI. Maybe, I am missing something, but this would be a very helpful feature... (If there is a way to achieve this already, please let me know!)

Thanks!

**Comment by VictorSanh** [comment]
Hi @lauritowal,

The easiest way there is right now is to include your user name into the list of additional user names to include in the toggle: https://github.com/bigscience-workshop/promptsource/blob/b860c0b2e06c027946d7ba874c83ef3cc101646a/promptsource/templates.py#L29

That way, your datasets will appear in promptsource. You can do that change locally since you are already installing from source.

**Comment by lauritowal** [comment]
Wouldn't that require to have the a template.yml file in the TEMPLATES_FOLDER_PATH ? I don't have a template.yml file for my dataset above...

**Comment by lauritowal** [comment]
Okay, I manually created one under /promptsource/templates/lauritowal/redefine_math/templates.yaml 

```
dataset: lauritowal/redefine_math
templates:
  02ff2949-0f45-4d97-941e-6fa4c0afbc2d: !Template
    answer_choices: 0 ||| 1
    id: 02ff2949-0f45-4d97-941e-6fa4c0afbc2f
    jinja: Question... {{text}} ||| {{ answer_choices [label] }}
    metadata: !TemplateMetadata
      choices_in_prompt: false
      languages:
      - en
      metrics:
      - Accuracy
      original_task: true
    name: Choices
    reference: ''
```
